- src/pages/ethdenver/index.js
Swag grab - reference announcements channel in discord
Bounties presentation - add time for livestream
ZK Rollups - update date, time and venue
Vega Bounties - remove as duplicate
> Content updates as plan firms up

- src/components/Incentive.js
- src/pages/community/contributors.js
- src/pages/community/index.js
- src/pages/key-concepts/index.js
Adding the data-cy attrs to incentives and contributors to assist with the e2e tests.
> Adding data-cy attributes to support e2e

- src/pages/talks/index.js
Correct typo in page meta data
> Update talks page index.js

- src/pages/key-concepts/index.js
Further boiling down the descriptions for two test concepts to check they look OK:
- Anti front-running protection 
- Permissionless market creation
> Update key concepts page

- src/content/papers/04-martingale-variates.md
- src/content/papers/05-model-calibration.md
- src/content/papers/06-fairness.md
- src/content/papers/07-liquidity.md
- src/content/papers/08-wendy-grows-up.md
> Update papers positions

- src/pages/community/ambassadors.js
Updated with non-technical and technical labels, and updated descriptions from Daigan / Mary.
> Ambassadors "Vega team" naming and description

- src/pages/governance/index.js
Added tagging to descriptions of phase 1 & 2, corrected a spelling mistake.
> Updating phase 1 & 2 descriptions to include tagging

- src/pages/market-creation/index.js
- Corrected "propoals" spelling mistake
- Added (Testnet) to voting call to action
- Updated link to see what markets exist already to the console market list 
- Updated testnet docs links to new doc site
> Market creation page updates to new doc site, spelling and (Testnet)

- src/pages/governance/index.js
Updated copy on intro to governance page following key messaging review (making it shorter)
> Intro to governance copy

- src/pages/develop/index.js
Updated heading on Develop from "CREATING THE FUTURE OF DEFI TOGETHER" to "DEVELOP ON VEGA"
> Update heading on Develop

- src/pages/governance/index.js
Updated description of the forum to tie in with the lifecycle step description.
> Copy change for the forum description

- src/pages/market-creation/index.js
Updated links to forum testnet governance rather than mainnet governance category
> Forum category links for market creation (Testnet)

- src/pages/market-creation/index.js
Updated submit step reflecting feedback from the team + copy changes / amends to line up with the governance lifecycle content.
> Updates to the Submit step and minor copy changes

- src/pages/governance/index.js
Updating description of the forum to include the sorts of things you can propose. 
Updating the description of voting to explain how this is still a commitment - they can be used for staking as well as voting on any/all active proposals, but cannot be used to trade.
> Update governance copy

- src/pages/community/events.js
Hadn't been updated when page was duplicated from the incentives and bounties page
> Update meta title and description of Events page

- src/components/Navigation/items/Community.js
- src/components/Navigation/items/Develop.js
Added report a security issue to community nav and develop nav under "get rewarded"
> Added report a security issue to community + develop nav

- locales/en/page.governance.json
- locales/es/page.governance.json
- src/pages/governance/index.js
Updating based on Mary's tweaks - 
Added "This is how the protocol powers the creation of decentralised financial products." to governance intro.
> Adding mission / vision words to governance intro

- src/pages/develop/index.js
Remove irrelevant market creation module
> Remove module on develop

- functions/latest-tweet.js
- locales/cn/page.key-concepts.json
- locales/en/page.key-concepts.json
- locales/es/page.key-concepts.json
- locales/ru/page.key-concepts.json
- src/components/NewsCard.js
allow for tweets with no images
prevent escaping of html chars in tweet text
> fix tweet errors

- src/pages/partners-backers/index.js
You'll need to check I haven't missed a div or something
> Remove markets and liquidity programme section

- src/pages/community/ambassadors.js
To this link - https://vegaprotocol.typeform.com/ambassadorappq4
> Updated all Application links

- src/components/Footer.js
- src/components/Navigation/items/Governance.js
- src/content/tools/index.json
- src/pages/bug-bounties/index.js
- src/pages/develop/index.js
- src/pages/governance/index.js
- src/pages/market-creation/index.js
- src/pages/use/index.js
- src/pages/wallet/index.js
This fixes various links to docs.vega.xyz since the url structure has changed
> Fix links to the docs site

- locales/cn/page.community.ambassadors.json
- locales/en/page.community.ambassadors.json
- locales/es/page.community.ambassadors.json
- locales/ru/page.community.ambassadors.json
- src/pages/community/ambassadors.js
Left the commented one in below, as Daigan wants to add it back later, when it's ready
> Removed mention of priority minting

- .prettierrc
- locales/cn/component.tool-box.json
- locales/en/component.tool-box.json
- locales/es/component.tool-box.json
- locales/ru/component.tool-box.json
- src/components/ToolBox.js
Fixes a translation key error in the ToolBox component
> Fix translation

- src/components/ButtonLink.js
- src/components/CalloutHero.js
- src/components/LatestNews.js
- src/components/NewsCard.js
- src/pages/key-concepts/index.js
- src/pages/use/index.js
Add link arrows to news block titles
> Vega latest improvements

- locales/cn/page.wallet.json
- locales/en/page.wallet.json
- locales/es/page.wallet.json
- locales/ru/page.wallet.json
- src/pages/wallet/index.js
- 'Mainnet' word added to primary download button
- Secondary button added to wallet page pointing to all wallet releases
> Link separately to the wallet release for Testnet

- src/pages/market-creation/index.js
Fixes a broken link...
@pennyandrews this should [fix this failing test](https://github.com/vegaprotocol/vega-website-cypress-tests/actions/runs/3484251645)
> Fix link to markets

- locales/es/page.wallet.json
Adds "(Mainnet)" in Spanish translation for the wallet download button
> Minor update to Spanish translation

- src/pages/community/ambassadors.js
> added />, cleaned code

- src/components/RoadMap.tsx
- src/content/roadmap/01/content.cn.md
- src/content/roadmap/01/content.en.md
- src/content/roadmap/01/content.es.md
- src/content/roadmap/01/content.ru.md
- src/content/roadmap/02/content.cn.md
- src/content/roadmap/02/content.en.md
- src/content/roadmap/02/content.es.md
- src/content/roadmap/02/content.ru.md
- src/content/roadmap/03/content.en.md
- src/content/roadmap/03/content.es.md
- src/content/roadmap/03/content.ru.md
- src/content/roadmap/04/content.cn.md
- src/content/roadmap/04/content.en.md
- src/content/roadmap/04/content.es.md
- src/content/roadmap/04/content.ru.md
- src/content/roadmap/05/content.cn.md
- src/content/roadmap/05/content.en.md
- src/content/roadmap/05/content.es.md
- src/content/roadmap/05/content.ru.md
- src/gatsby-types.d.ts
Add 'current status' tag to roadmap component
Change date text to be '2022 H1' instead of 'H1 2022'
Closes #320
> Add current status tag to roadmap

- src/components/Ticker.js
Updated API url from `api.token.vega.xyz` to `api.vega.xyz`.
> Fix home page ticker

- locales/cn/page.external-link.json
- locales/en/page.external-link.json
- locales/es/page.external-link.json
- locales/ru/page.external-link.json
- src/gatsby-types.d.ts
- src/pages/external-link/index.tsx
- Update text on interstitial page
- Add translations banner
> Update text on interstitial page

- src/components/Calendar.js
- src/components/CalendarEvent.js
Adding data attributes around events for cypress E2E Tests
> Adding data attributes around events

- src/components/Ticker.js
> fix incorrect number of validators

- src/pages/wallet/index.js
Adding some data attributes to the wallet page for cypress tests
> Minor-Data Attributes Wallet

- src/components/Layout.js
Update Layout.js to update mainnet sims CTA
> Update Mainnet Sims CTA

- src/gatsby-types.d.ts
- src/pages/bug-bounties/index.js
Adding some test attributes for future tests
> Minor-BugBountiesDataAttributes

- src/components/Layout.js
> Update mainnet sims banner in Layout.js

- src/components/Layout.js
- src/components/RoadMap.tsx
- src/content/roadmap/03/content.en.md
- src/pages/key-concepts/index.js
- src/pages/use/index.js
> Roadmap updates for alpha mainnet launch

- src/content/roadmap/03/content.cn.md
- src/content/roadmap/03/content.en.md
- src/content/roadmap/03/content.es.md
- src/content/roadmap/03/content.ko.md
- src/content/roadmap/03/content.ru.md
- src/content/roadmap/04/content.cn.md
- src/content/roadmap/04/content.en.md
- src/content/roadmap/04/content.es.md
- src/content/roadmap/04/content.ko.md
- src/content/roadmap/04/content.ru.md
- src/content/roadmap/05/content.cn.md
- src/content/roadmap/05/content.en.md
- src/content/roadmap/05/content.es.md
- src/content/roadmap/05/content.ko.md
- src/content/roadmap/05/content.ru.md
close #580 
This change updates the text content for the roadmap items on the website.
> chore: update roadmap listings

- src/content/roadmap/03/content.cn.md
- src/content/roadmap/03/content.en.md
- src/content/roadmap/03/content.es.md
- src/content/roadmap/03/content.ko.md
- src/content/roadmap/03/content.ru.md
Updates the  alpha mainnet roadmap list items
> chore: update alpha mainnet roadmap list

- interstitial-allow.json
- src/components/Home/Markets.tsx
- src/pages/market-creation/index.js
Correct links to all markets page on console
> Update Console all markets list URL

- .github/workflows/E2ETests.yml
- CODEOWNERS
Add a codeowner file, and set vinayandani9 to be reviewer on all pr related to the locales folder.
> chore: add vinayandani9 as codeowner for all locales transalations

- vercel.json
The new vercel setup is missing some of the Netlify redirects
> Add missing redirects

- src/pages/liquidity-provision/index.tsx
- src/pages/liquidity-provision/liquidity-provision.css
> add sorting comparators for most liquidity provider columns

- src/pages/liquidity-provision/index.tsx
> filter STATE_PROPOSED markets from the lp dashboard

- src/content/talks/0048-inside-crypto-21.co/index.en.md
> Adding new talk

- api/latest-tweet.js
- package.json
- src/components/NewsCard.tsx
- yarn.lock
Closes #824 
Implements Redis to cache the latest tweet from Twitter's API
> feat: add redis caching to latest tweet

- locales/vi/component.liquidity-provision.json
Vietnamese Update component.liquidity-provision.json
> Vietnamese Update component.liquidity-provision.json

- locales/vi/component.latest-news.json
Vietnamese Update component.latest-news.json
> Vietnamese Update component.latest-news.json

- locales/vi/component.incentives.json
Vietnamese Update component.incentives.json
> Vietnamese Update component.incentives.json

- locales/vi/component.incentive.json
Vietnames Update component.incentive.json
> Vietnames Update component.incentive.json

- locales/vi/component.epoch-countdown.json
Vietnamese Update component.epoch-countdown.json
> Vietnamese Update component.epoch-countdown.json

- locales/vi/component.fairground.json
Vietnamese Update component.fairground.json
> Vietnamese Update component.fairground.json

- locales/vi/component.contributor.json
Vietnamese Update component.contributor.json
> Vietnamese Update component.contributor.json

- locales/vi/component.blog-posts.json
Vietnamese Update component.blog-posts.json
> Vietnamese Update component.blog-posts.json

- locales/vi/component.as-seen-on.json
vietnamese Update component.as-seen-on.json
> vietnamese Update component.as-seen-on.json

- locales/vi/component.ambassador-leaderboard.json
Update component.ambassador-leaderboard.json
> Vnese Update component.ambassador-leaderboard.json

- locales/vi/component.proposal.json
VietnameseUpdate component.proposal.json
> VietnameseUpdate component.proposal.json

- locales/vi/component.proposals.json
Vietnamese Update component.proposals.json
> Vietnamese Update component.proposals.json

- locales/vi/component.reward-fees.json
vietnamese Update component.reward-fees.json
> vietnamese Update component.reward-fees.json

- locales/vi/component.calendar-event.json
Vietnamese Update component.calendar-event.json
> Vietnamese Update component.calendar-event.json

- locales/vi/component.statistics.json
Vietnamese Update component.statistics.json
> Vietnamese Update component.statistics.json

- locales/vi/component.tool-box.json
Vietnamese Update component.tool-box.json
> Vietnamese Update component.tool-box.json

- locales/vi/page.careers.json
Vietnamese Update page.careers.json
> Vietnamese Update page.careers.json

- locales/vi/page.community.swag.json
Vietnamese Update page.community.swag.json
> Vietnamese Update page.community.swag.json

- locales/vi/page.insights.json
VietnameseUpdate page.insights.json
> VietnameseUpdate page.insights.json

- locales/vi/page.talks.json
Vietnamese Update page.talks.json
> Vietnamese Update page.talks.json

- locales/vi/component.statistics.json
- locales/vi/page.key-concepts.json
- src/content/papers/implementations/002-wendy-grows-up/index.es.md
- src/content/papers/implementations/004-model-calibration/index.es.md
Fixes some formatting errors introduced when merging the latest translations
> fix: fix locale and markdown syntax errors

- locales/cn/page.index.json
- locales/cn/page.index_old.json
- locales/en/page.index.json
- locales/en/page.index_old.json
- locales/es/page.index.json
- locales/es/page.index_old.json
- locales/ko/page.index.json
- locales/ko/page.index_old.json
- locales/ru/page.index.json
- locales/ru/page.index_old.json
- locales/vi/page.index.json
- locales/vi/page.index_old.json
- src/pages/index.tsx
Change title tag to 'Vega Protocol - Futures DEX"
> fix: correct title meta

- locales/vi/common.json
> vietnamese Update common.json

- locales/vi/component.blog-post.json
Vietnamese Update component.blog-post.json
> Vietnamese Update component.blog-post.json

- locales/vi/component.navigation_old.json
update vietnamese Update component.navigation_old.json
> update vietnamese Update component.navigation_old.json

- locales/vi/component.latest-news.json
update vietnamese Update component.latest-news.json
> update vietnamese Update component.latest-news.json

- locales/vi/component.news-item.json
Vietnamese Update component.news-item.json
> Vietnamese Update component.news-item.json

- locales/vi/component.partners-backers.json
Vietnamese Update component.partners-backers.json
> Vietnamese Update component.partners-backers.json

- locales/vi/page.community.ambassadors_old.json
Vietnamese Update page.community.ambassadors_old.json
> Vietnamese Update page.community.ambassadors_old.json

- locales/vi/page.community_old.json
Vietnamese Update page.community_old.json
> Vietnamese Update page.community_old.json

- locales/vi/page.develop.json
Vietnamese Update page.develop.json
> Vietnamese Update page.develop.json

- locales/vi/page.faqs.json
Vietnamese Update page.faqs.json
> Vietnamese Update page.faqs.json

- locales/vi/page.governance_old.json
Vietnamese Update page.governance_old.json
> Vietnamese Update page.governance_old.json

- locales/vi/page.index_old.json
Vietnamese Update page.index_old.json
> Vietnamese Update page.index_old.json

- .github/workflows/E2ETests.yml
- src/components/LatestNews.tsx
- src/components/PartnerBackers.tsx
- src/pages/developers/index.js
- src/pages/restricted/index.js
- vercel.json
Redirect some countries to a 'restricted' page.
- Add geo redirects
- Add restricted page
> feat: add geo restrictions

- locales/cn/page.develop.json
- locales/cn/page.develop_old.json
- locales/en/page.develop.json
- locales/en/page.develop_old.json
- locales/es/page.develop.json
- locales/es/page.develop_old.json
- locales/ko/page.develop.json
- locales/ko/page.develop_old.json
- locales/ru/page.develop.json
- locales/ru/page.develop_old.json
- locales/vi/page.develop.json
- locales/vi/page.develop_old.json
- src/components/Home/Markets.tsx
- src/components/MarketTile.tsx
- src/utils/vega/Markets.ts
Fixed market tiles on homepage to show only active and suspended markets. Also corrected the labelling for suspended markets.
> Fix market tiles

- src/hooks/statistics/use-total-volume.ts
fix: add pagination to api request to grab all results rather than fi…
> Fix total volume

- src/pages/wallet/index.js
The FF extension URL needed an update
> Update extension link for firefox
