vegaprotocol/vega.xyz

src/components/Container.js
src/pages/careers/index.js
src/pages/community/contributors.js
src/pages/community/index.js
src/pages/develop/index.js
src/pages/index.js
src/pages/key-concepts/index.js
src/pages/papers/index.js
src/pages/partners-backers/index.js
src/pages/talks/index.js
src/pages/use/index.js

Adding an attribute to the Container component, `data-cy`. This has been added so that selectors in end-to-end tests are robust, readable and more easily manageable.
The attr will only be applied if specified on a page's instance of the component. To specify this attribute add `dataCy={string}` to the Container, where `string` is the attribute value, e.g. `<Container dataCy={'main'}>`.
I have added this attribute to the following pages:
/key-concepts
/papers
/talks
/develop
/use
/community
/community/contributors/
/careers
/partners-backers

Add data cy attr to container

---

src/pages/develop/index.js

Fixes the "page not found" when clicking the wallet link under develop.

Fix broken wallet link on develop page

---

src/pages/key-concepts/index.js

Hiya, the data-cy attr is only generated when attached to a container. `dataCy={"main"}` was added to a div so that was in effect hardcoded. I've updated the attr on the div to be `data-cy="main"`, just something to be aware of in case it is added to a div/non-Container component in the future.

Updating data-cy to be hardcoded on div

---

static/_redirects

This adds a redirect URL that is needed for Builders Club to support our work and also our BC recruitment on the ground at ETHcc

Redirect to builders club register interest form

---

src/pages/develop/index.js

removed redundant /en from the URL which was causing it not to work and failing our cypress tests

Fix broken link to roadmap on develop page

---

src/pages/governance/index.js

Changing 'Token Interface' title on card to 'Governance' in line with the new Use Vega tools naming

Update card title on governance page

---

src/pages/key-concepts/index.js

Remove unnecessary words on read more about links on anti front-running protection
Removed 'built in' from anti front-running protection as duplicates liquidity incentives
Updated built in liquidity incentives title and copy
Updated efficient price discovery copy
Updated optimised for high capital efficiency copy

Update to reduce copy on key concepts page

---

src/pages/market-creation/index.js

Removed "Easy to" from attract liquidity statements following review.

Legal input - removing "easy to" + copy changes

---

src/pages/key-concepts/index.js

Removing link to a blog post from the built in liquidity incentives section as it doesn't help you understand liquidity at vega, it's instead about providing liquidity for a pool on sushiswap.
https://blog.vega.xyz/sushiswap-how-to-get-vega-liquidity-rewards-9848e4cadee9

Removing sushiswap blogpost link

---

src/pages/develop/index.js

This fixes a broken link in the /develop page on button titled 'Explore the docs'

Fix broken link for 'Explore the docs' button

---

src/pages/market-creation/index.js

tutorials/committing-liquidity instead of tutorials/liquidity-provision

Fix broken docs link on market creation page

---

.github/workflows/E2ETests.yml

New workflow for running E2E tests on PRs.
I have commented out a few features as they require the cypress record key.
Someone with admin access to the project will need to add the secret, and then we can enable the commented out features.

Create E2ETests yml

---

src/content/roadmap/03/content.en.md
src/content/roadmap/03/content.es.md
src/content/roadmap/03/content.ru.md

I think that the link to the milestone gives a better more accurate view on whats remaining as it also includes PRs and not just issues.
I think this then will match the [Alpha mainnet](https://github.com/orgs/vegaprotocol/projects/125/views/2) project board and cause less confusion.

chore: update link to Oregon Trail whats left

---

.github/workflows/E2ETests.yml

Update E2E action to record runs. Also enable parallel test running to speed up the tests slightly.

Update E2E action to record runs

---

src/components/UI/Table.js
src/gatsby-types.d.ts
src/pages/key-concepts/index.js
src/pages/use/index.js

Use overflow auto instead of scroll to ensure scroll bars only show when needed

Prevent redundant scrollbars showing beneath tabs

---

src/pages/rewards/index.js

Dave has some concerns about whether we are sufficiently explaining / justifying this figure so hiding until decisions have been made / new copy provided

Hide APY on rewards page

---

src/pages/rewards/index.js

It appeared to be a copy past job of the develop page so was showing the title and description for the develop page. I've changed this to be rewards specific

Fix title and description of rewards page

---

src/pages/wallet/index.js

Update links in the website for the latest fairground deployment of 0.70.x
https://github.com/vegaprotocol/vegawallet-desktop/releases/tag/v0.11.0
https://github.com/vegaprotocol/vega/releases/tag/v0.70.1

chore: update fairground wallet download links

---

src/pages/wallet/index.js

Update the desktop wallet download version from 0.11.0 to 0.11.1

chore: update fairground wallet to 0.11.1

---

src/pages/wallet/index.js

Update to download patch version 0.11.2 for fairground / testnet users
https://github.com/vegaprotocol/vegawallet-desktop/releases/tag/v0.11.2

chore: Update fairground wallet download version

---

src/pages/wallet/index.js

update to v0.11.3
https://github.com/vegaprotocol/vegawallet-desktop/releases/tag/v0.11.3

chore: bump fairground wallet version

---

src/pages/wallet/index.js

Update fairground wallet version to 0.12.0 for the website download

chore: update fairground wallet version to 0.12.0

---

src/pages/wallet/index.js

DO NOT MERGE UNTIL:
- https://github.com/vegaprotocol/vegawallet-desktop/issues/683 (ignore patch version compatibility check)
- https://github.com/vegaprotocol/vegawallet-desktop/pull/685 (release 0.12.1)
This PR updates the links for the download for the desktop wallet to be used for mainnet (0.71.4)

feat: update links for the mainnet wallet download

---

interstitial-allow.json
netlify.toml
src/pages/external-link/index.tsx

The interstitial page will need to direct users to IPFS deploys for some
apps. Rather than require the gateway URLs to be hardcoded somewhere,
this PR extends the allow list JSON file to have a variable for
configuring an IPFS gateway, and adds IPFS and IPNS specific support.
Also fixes a bug whereby disallowed links would still be redirected,
even after showing a 404.
- Fix redirect on notFound pages
- Add ipfs and ipns specific support
- Update interstitial-allow.json format
Closes #554

Fix redirect of disallowed links, add ipfs hash list

---

src/pages/external-link/index.tsx

The previous interstitial implementation didn't allow for deep linking in to IPFS apps. This PR passes `#anchors` through to the IPFS and IPNS destinations.

Perserve hash routes when creating ipfs link

---

src/hooks/use-market-liquidity.ts

This will return only live LPs, which is the number we want (it should match the value in supplied stake).
This PR gets the _correct number_ from the API - but does not resolve the decimal place issues for either the Total Staked or Fee - both of which will need a change on the healthbar component in the monorepo, which I'll follow this with.

fix: Add 'live' argument to liquidityProvisionsConnection query

---

src/pages/liquidity-provision/index.tsx

Our % staked was incorrectly calculating percentages for some markets. We were doing some casting and rounding of the values _before_ comparing them which doesn't seem necessary, so I've removed it. Much simpler, and seems to produce the correct results.

fix: supplied stake percentage

---

src/pages/wallet/index.js

Change the file extension for the two windows files from .zip to .exe

Update Wallet Windows Download URLs

---

src/components/Home/LiquidityProvision.tsx
src/hooks/use-markets.ts
src/pages/liquidity-provision/index.tsx

i.e.
'STATE_UNSPECIFIED',
'STATE_PENDING',
'STATE_ACTIVE',
'STATE_SUSPENDED'
Fixes: https://github.com/vegaprotocol/vega.xyz/issues/1022

fix: filter liquidity tiles to markets in states we care about
